"""add pipeline_configs table

Revision ID: ebd467d9f074
Revises: 
Create Date: 2026-04-13 20:32:10.682094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd467d9f074'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('wp_username', sa.String(length=255), nullable=False),
    sa.Column('wp_app_password_encrypted', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('key_name', sa.String(length=255), nullable=False),
    sa.Column('value_encrypted', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'key_name', name='uq_credentials_provider_key_name')
    )
    op.create_table('pipeline_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('blog_id', sa.Uuid(), nullable=False),
    sa.Column('articles_per_week', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=255), nullable=False),
    sa.Column('image_provider', sa.String(length=255), nullable=False),
    sa.Column('content_tone', sa.String(length=255), nullable=False),
    sa.Column('default_category', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blog_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_configs')
    op.drop_table('credentials')
    op.drop_table('blogs')
    # ### end Alembic commands ###
