// ---------------------------------------------------------------------------
// Realistic mock data fixtures for all entity types
// Used as SWR fallback during development
// ---------------------------------------------------------------------------

import type {
  Blog,
  PipelineConfig,
  Run,
  Article,
  Credential,
} from './types';

// ---------------------------------------------------------------------------
// Blogs — 3 realistic blog brands
// ---------------------------------------------------------------------------

export const mockBlogs: Blog[] = [
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    name: 'The Weekend Folio',
    slug: 'the-weekend-folio',
    url: 'https://theweekendfolio.com',
    wp_username: 'admin',
    wp_application_password: '********',
    is_active: true,
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-04-12T14:30:00Z',
    profile_prompt: 'Write in a warm, conversational tone about weekend lifestyle topics. Focus on practical tips and personal experiences.',
    fallback_category: 'Lifestyle',
    deprioritized_category: 'Uncategorized',
    category_keywords: {
      'Weekend Getaways': ['travel', 'road trip', 'weekend escape', 'day trip'],
      'Home Projects': ['DIY', 'home improvement', 'crafts', 'renovation'],
      'Outdoor Living': ['patio', 'garden', 'bbq', 'outdoor decor'],
    },
    pinterest_board_map: {
      'Weekend Getaways': 'weekend-getaways-inspiration',
      'Home Projects': 'diy-home-projects',
    },
    seed_keywords: ['weekend activities', 'saturday projects', 'lazy sunday ideas'],
  },
  {
    id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    name: 'Your Midnight Desk',
    slug: 'your-midnight-desk',
    url: 'https://yourmidnightdesk.com',
    wp_username: 'editor',
    wp_application_password: '********',
    is_active: true,
    created_at: '2026-02-05T11:00:00Z',
    updated_at: '2026-04-10T08:15:00Z',
    profile_prompt: 'Write in an editorial, food-focused style with a touch of sophistication. Include detailed recipes and cultural context.',
    fallback_category: 'Recipes',
    deprioritized_category: 'Uncategorized',
    category_keywords: {
      'Dinner Recipes': ['dinner', 'main course', 'easy dinner', 'family meal'],
      'Baking': ['baking', 'dessert', 'cake', 'pastry'],
      'Kitchen Tips': ['cooking tips', 'kitchen hacks', 'meal prep'],
    },
    pinterest_board_map: {
      'Dinner Recipes': 'easy-dinner-recipes',
      'Baking': 'baking-inspiration',
    },
    seed_keywords: ['easy recipes', 'comfort food', 'meal prep ideas'],
  },
  {
    id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    name: 'The Sunday Patio',
    slug: 'the-sunday-patio',
    url: 'https://thesundaypatio.com',
    wp_username: 'admin',
    wp_application_password: '********',
    is_active: false,
    created_at: '2026-03-15T13:00:00Z',
    updated_at: '2026-04-01T16:45:00Z',
    profile_prompt: 'Write about outdoor living with an emphasis on seasonal gardening, patio design, and backyard entertaining.',
    fallback_category: 'Outdoor Living',
    deprioritized_category: 'Uncategorized',
    category_keywords: {
      'Gardening': ['garden', 'plants', 'landscaping', 'flower beds'],
      'Patio Design': ['patio', 'outdoor furniture', 'deck', 'pergola'],
      'Backyard Entertaining': ['bbq', 'outdoor party', 'fire pit', 'grilling'],
    },
    pinterest_board_map: {
      'Gardening': 'garden-inspiration',
      'Patio Design': 'patio-design-ideas',
    },
    seed_keywords: ['patio ideas', 'garden design', 'outdoor living'],
  },
];

// ---------------------------------------------------------------------------
// Pipeline Configs — one per blog
// ---------------------------------------------------------------------------

export const mockPipelineConfigs: Record<string, PipelineConfig> = {
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890': {
    id: 'pc-001-aaaa-bbbb-cccc-111111111111',
    blog_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    llm_provider: 'deepseek',
    image_provider: 'fal',
    llm_model: 'deepseek-chat',
    image_model: 'fal-ai/flux/dev',
    trends_region: 'US',
    trends_range: '3m',
    trends_top_n: 15,
    pinclicks_max_records: 20,
    winners_count: 5,
    publish_status: 'draft',
    csv_cadence_minutes: 240,
    pin_template_mode: 'center_strip',
    max_concurrent_articles: 3,
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-04-12T14:30:00Z',
  },
  'b2c3d4e5-f6a7-8901-bcde-f12345678901': {
    id: 'pc-002-aaaa-bbbb-cccc-222222222222',
    blog_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    llm_provider: 'deepseek',
    image_provider: 'fal',
    llm_model: 'deepseek-chat',
    image_model: 'fal-ai/flux/dev',
    trends_region: 'GLOBAL',
    trends_range: '12m',
    trends_top_n: 20,
    pinclicks_max_records: 25,
    winners_count: 8,
    publish_status: 'publish',
    csv_cadence_minutes: 120,
    pin_template_mode: 'bold_header',
    max_concurrent_articles: 5,
    created_at: '2026-02-05T11:00:00Z',
    updated_at: '2026-04-10T08:15:00Z',
  },
  'c3d4e5f6-a7b8-9012-cdef-123456789012': {
    id: 'pc-003-aaaa-bbbb-cccc-333333333333',
    blog_id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    llm_provider: 'deepseek',
    image_provider: 'fal',
    llm_model: 'deepseek-chat',
    image_model: 'fal-ai/flux/dev',
    trends_region: 'US',
    trends_range: '6m',
    trends_top_n: 10,
    pinclicks_max_records: 15,
    winners_count: 3,
    publish_status: 'draft',
    csv_cadence_minutes: 360,
    pin_template_mode: 'minimal',
    max_concurrent_articles: 2,
    created_at: '2026-03-15T13:00:00Z',
    updated_at: '2026-04-01T16:45:00Z',
  },
};

// ---------------------------------------------------------------------------
// Credentials
// ---------------------------------------------------------------------------

export const mockCredentials: Credential[] = [
  {
    id: 'cr-001-1111-2222-3333-444444444444',
    provider: 'deepseek',
    key_name: 'DEEPSEEK_API_KEY',
    created_at: '2026-01-05T08:00:00Z',
    updated_at: '2026-01-05T08:00:00Z',
  },
  {
    id: 'cr-002-1111-2222-3333-555555555555',
    provider: 'fal',
    key_name: 'FAL_KEY',
    created_at: '2026-01-05T08:01:00Z',
    updated_at: '2026-01-05T08:01:00Z',
  },
  {
    id: 'cr-003-1111-2222-3333-666666666666',
    provider: 'brave',
    key_name: 'BRAVE_API_KEY',
    created_at: '2026-01-05T08:02:00Z',
    updated_at: '2026-03-10T09:30:00Z',
  },
  {
    id: 'cr-004-1111-2222-3333-777777777777',
    provider: 'pinclicks',
    key_name: 'PINCLICKS_SESSION',
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-04-01T07:00:00Z',
  },
];

// ---------------------------------------------------------------------------
// Runs — mix of statuses
// ---------------------------------------------------------------------------

export const mockRuns: Run[] = [
  {
    id: 'rn-001-aaaa-bbbb-cccc-r11111111111',
    blog_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    status: 'generating',
    run_code: 'RUN-20260414-001',
    phase: 'generating',
    seed_keywords: ['weekend brunch ideas', 'sunday morning recipes', 'lazy weekend meals'],
    config_snapshot: { winners_count: 5, publish_status: 'draft' },
    results_summary: { trends_found: 15, pinclicks_analyzed: 45, winners: 5 },
    csv_path: null,
    articles_total: 5,
    articles_completed: 2,
    articles_failed: 0,
    error_message: null,
    created_at: '2026-04-14T08:00:00Z',
    started_at: '2026-04-14T08:00:15Z',
    completed_at: null,
  },
  {
    id: 'rn-002-aaaa-bbbb-cccc-r22222222222',
    blog_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    status: 'completed',
    run_code: 'RUN-20260413-003',
    phase: 'completed',
    seed_keywords: ['comfort food classics', 'one pot meals', 'quick dinner ideas'],
    config_snapshot: { winners_count: 8, publish_status: 'publish' },
    results_summary: { trends_found: 20, pinclicks_analyzed: 60, winners: 8 },
    csv_path: 'tmp/pinterest_engine/20260413_120000/pinterest_bulk_upload_your_midnight_desk.csv',
    articles_total: 8,
    articles_completed: 7,
    articles_failed: 1,
    error_message: null,
    created_at: '2026-04-13T12:00:00Z',
    started_at: '2026-04-13T12:00:10Z',
    completed_at: '2026-04-13T14:32:45Z',
  },
  {
    id: 'rn-003-aaaa-bbbb-cccc-r33333333333',
    blog_id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    status: 'failed',
    run_code: 'RUN-20260412-002',
    phase: 'failed',
    seed_keywords: ['spring garden tips', 'raised bed gardening', 'container gardening'],
    config_snapshot: { winners_count: 3, publish_status: 'draft' },
    results_summary: { trends_found: 10, pinclicks_analyzed: 12, winners: 3 },
    csv_path: null,
    articles_total: 3,
    articles_completed: 1,
    articles_failed: 2,
    error_message: 'DeepSeek API rate limit exceeded — run halted after 3 retries',
    created_at: '2026-04-12T15:30:00Z',
    started_at: '2026-04-12T15:30:05Z',
    completed_at: '2026-04-12T16:10:22Z',
  },
  {
    id: 'rn-004-aaaa-bbbb-cccc-r44444444444',
    blog_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    status: 'pending',
    run_code: 'RUN-20260414-005',
    phase: 'pending',
    seed_keywords: ['patio makeover ideas', 'outdoor lighting', 'garden furniture trends'],
    config_snapshot: {},
    results_summary: {},
    csv_path: null,
    articles_total: 0,
    articles_completed: 0,
    articles_failed: 0,
    error_message: null,
    created_at: '2026-04-14T09:15:00Z',
    started_at: null,
    completed_at: null,
  },
  {
    id: 'rn-005-aaaa-bbbb-cccc-r55555555555',
    blog_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    status: 'running',
    run_code: 'RUN-20260414-004',
    phase: 'publishing',
    seed_keywords: ['air fryer recipes', 'quick baking ideas', 'no-bake desserts'],
    config_snapshot: { winners_count: 5, publish_status: 'draft' },
    results_summary: { trends_found: 18, pinclicks_analyzed: 50, winners: 5 },
    csv_path: null,
    articles_total: 5,
    articles_completed: 4,
    articles_failed: 0,
    error_message: null,
    created_at: '2026-04-14T07:00:00Z',
    started_at: '2026-04-14T07:00:08Z',
    completed_at: null,
  },
];

// ---------------------------------------------------------------------------
// Articles — mix of statuses across blogs and runs
// ---------------------------------------------------------------------------

export const mockArticles: Article[] = [
  {
    id: 'ar-001-aaaa-bbbb-cccc-a11111111111',
    blog_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    run_id: 'rn-001-aaaa-bbbb-cccc-r11111111111',
    keyword: 'weekend brunch ideas',
    title: '15 Weekend Brunch Ideas That Will Transform Your Sunday Morning',
    slug: 'weekend-brunch-ideas-transform-sunday-morning',
    status: 'published',
    wp_post_id: 1247,
    wp_permalink: 'https://theweekendfolio.com/weekend-brunch-ideas-transform-sunday-morning/',
    error_message: null,
    created_at: '2026-04-14T08:05:00Z',
    completed_at: '2026-04-14T08:22:30Z',
    seo_title: '15 Weekend Brunch Ideas for the Perfect Sunday Morning',
    meta_description: 'Discover 15 creative weekend brunch ideas that will make your Sunday mornings unforgettable. From sweet pancakes to savory egg bakes, we have you covered.',
    focus_keyword: 'weekend brunch ideas',
    content_markdown: '# 15 Weekend Brunch Ideas That Will Transform Your Sunday Morning\n\nSunday mornings are made for leisurely brunches...\n\n## Sweet Classics Reimagined\n\n...',
    content_html: '<h1>15 Weekend Brunch Ideas That Will Transform Your Sunday Morning</h1><p>Sunday mornings are made for leisurely brunches...</p><h2>Sweet Classics Reimagined</h2><p>...</p>',
    hero_image_prompt: 'A beautiful spread of brunch dishes on a rustic wooden table with morning light streaming through a window',
    hero_image_url: 'https://fal.media/files/hero-brunch-abc123.jpg',
    detail_image_prompt: 'Close-up of fluffy pancakes with maple syrup and fresh berries',
    detail_image_url: 'https://fal.media/files/detail-pancakes-xyz789.jpg',
    pin_title: '15 Weekend Brunch Ideas You Need to Try',
    pin_description: 'Transform your Sunday morning with these amazing brunch recipes!',
    pin_text_overlay: '15 WEEKEND BRUNCH IDEAS',
    pin_image_url: 'https://fal.media/files/pin-brunch-def456.jpg',
    category_name: 'Lifestyle',
    generation_attempts: 1,
    validation_errors: [],
    brain_output: null,
  },
  {
    id: 'ar-002-aaaa-bbbb-cccc-a22222222222',
    blog_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    run_id: 'rn-001-aaaa-bbbb-cccc-r11111111111',
    keyword: 'sunday morning recipes',
    title: '10 Easy Sunday Morning Recipes for a Relaxing Weekend',
    slug: 'easy-sunday-morning-recipes-relaxing-weekend',
    status: 'generating',
    wp_post_id: null,
    wp_permalink: null,
    error_message: null,
    created_at: '2026-04-14T08:10:00Z',
    completed_at: null,
    seo_title: null,
    meta_description: null,
    focus_keyword: 'sunday morning recipes',
    content_markdown: null,
    content_html: null,
    hero_image_prompt: null,
    hero_image_url: null,
    detail_image_prompt: null,
    detail_image_url: null,
    pin_title: null,
    pin_description: null,
    pin_text_overlay: null,
    pin_image_url: null,
    category_name: null,
    generation_attempts: 0,
    validation_errors: [],
    brain_output: null,
  },
  {
    id: 'ar-003-aaaa-bbbb-cccc-a33333333333',
    blog_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    run_id: 'rn-001-aaaa-bbbb-cccc-r11111111111',
    keyword: 'lazy weekend meals',
    title: null,
    slug: null,
    status: 'pending',
    wp_post_id: null,
    wp_permalink: null,
    error_message: null,
    created_at: '2026-04-14T08:12:00Z',
    completed_at: null,
    seo_title: null,
    meta_description: null,
    focus_keyword: null,
    content_markdown: null,
    content_html: null,
    hero_image_prompt: null,
    hero_image_url: null,
    detail_image_prompt: null,
    detail_image_url: null,
    pin_title: null,
    pin_description: null,
    pin_text_overlay: null,
    pin_image_url: null,
    category_name: null,
    generation_attempts: 0,
    validation_errors: [],
    brain_output: null,
  },
  {
    id: 'ar-004-aaaa-bbbb-cccc-a44444444444',
    blog_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    run_id: 'rn-002-aaaa-bbbb-cccc-r22222222222',
    keyword: 'comfort food classics',
    title: '7 Comfort Food Classics That Never Go Out of Style',
    slug: 'comfort-food-classics-never-go-out-of-style',
    status: 'published',
    wp_post_id: 892,
    wp_permalink: 'https://yourmidnightdesk.com/comfort-food-classics-never-go-out-of-style/',
    error_message: null,
    created_at: '2026-04-13T12:05:00Z',
    completed_at: '2026-04-13T12:18:45Z',
    seo_title: '7 Comfort Food Classics That Never Go Out of Style',
    meta_description: 'From creamy mac and cheese to hearty pot roast, these 7 comfort food classics will warm your soul and bring back fond memories.',
    focus_keyword: 'comfort food classics',
    content_markdown: '# 7 Comfort Food Classics That Never Go Out of Style\n\nThere\'s something magical about comfort food...\n\n## The Mac and Cheese That Started It All\n\n...',
    content_html: '<h1>7 Comfort Food Classics That Never Go Out of Style</h1><p>There\'s something magical about comfort food...</p><h2>The Mac and Cheese That Started It All</h2><p>...</p>',
    hero_image_prompt: 'A cozy kitchen table laden with classic comfort food dishes',
    hero_image_url: 'https://fal.media/files/hero-comfort-mno123.jpg',
    detail_image_prompt: 'Creamy mac and cheese in a cast iron skillet',
    detail_image_url: 'https://fal.media/files/detail-mac-pqr456.jpg',
    pin_title: '7 Comfort Food Classics Everyone Loves',
    pin_description: 'These timeless comfort food recipes will never let you down!',
    pin_text_overlay: '7 COMFORT FOOD CLASSICS',
    pin_image_url: 'https://fal.media/files/pin-comfort-stu789.jpg',
    category_name: 'Dinner Recipes',
    generation_attempts: 1,
    validation_errors: [],
    brain_output: null,
  },
  {
    id: 'ar-005-aaaa-bbbb-cccc-a55555555555',
    blog_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    run_id: 'rn-002-aaaa-bbbb-cccc-r22222222222',
    keyword: 'one pot meals',
    title: null,
    slug: null,
    status: 'failed',
    wp_post_id: null,
    wp_permalink: null,
    error_message: 'Content validation failed after 3 repair attempts: article too short (347 words, minimum 800)',
    created_at: '2026-04-13T12:10:00Z',
    completed_at: '2026-04-13T12:25:00Z',
    seo_title: null,
    meta_description: null,
    focus_keyword: 'one pot meals',
    content_markdown: null,
    content_html: null,
    hero_image_prompt: null,
    hero_image_url: null,
    detail_image_prompt: null,
    detail_image_url: null,
    pin_title: null,
    pin_description: null,
    pin_text_overlay: null,
    pin_image_url: null,
    category_name: null,
    generation_attempts: 3,
    validation_errors: ['Article too short: 347 words (minimum 800)', 'Missing H2 subheadings'],
    brain_output: null,
  },
  {
    id: 'ar-006-aaaa-bbbb-cccc-a66666666666',
    blog_id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    run_id: 'rn-003-aaaa-bbbb-cccc-r33333333333',
    keyword: 'spring garden tips',
    title: 'Essential Spring Garden Tips for a Blooming Season',
    slug: 'essential-spring-garden-tips-blooming-season',
    status: 'published',
    wp_post_id: 534,
    wp_permalink: 'https://thesundaypatio.com/essential-spring-garden-tips-blooming-season/',
    error_message: null,
    created_at: '2026-04-12T15:35:00Z',
    completed_at: '2026-04-12T15:52:10Z',
    seo_title: 'Essential Spring Garden Tips for a Blooming Season',
    meta_description: 'Get your garden ready for spring with these essential tips. From soil preparation to planting schedules, everything you need to know.',
    focus_keyword: 'spring garden tips',
    content_markdown: '# Essential Spring Garden Tips for a Blooming Season\n\nSpring is the perfect time to refresh your garden...\n\n## Preparing Your Soil\n\n...',
    content_html: '<h1>Essential Spring Garden Tips for a Blooming Season</h1><p>Spring is the perfect time to refresh your garden...</p><h2>Preparing Your Soil</h2><p>...</p>',
    hero_image_prompt: 'A vibrant spring garden with blooming flowers and fresh green shoots',
    hero_image_url: 'https://fal.media/files/hero-spring-vwx123.jpg',
    detail_image_prompt: 'Close-up of hands planting seedlings in rich garden soil',
    detail_image_url: 'https://fal.media/files/detail-soil-yza456.jpg',
    pin_title: 'Spring Garden Tips You Need Now',
    pin_description: 'Prepare your garden for a beautiful spring bloom with these expert tips!',
    pin_text_overlay: 'SPRING GARDEN TIPS',
    pin_image_url: 'https://fal.media/files/pin-spring-bcd789.jpg',
    category_name: 'Gardening',
    generation_attempts: 1,
    validation_errors: [],
    brain_output: null,
  },
  {
    id: 'ar-007-aaaa-bbbb-cccc-a77777777777',
    blog_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    run_id: 'rn-005-aaaa-bbbb-cccc-r55555555555',
    keyword: 'air fryer recipes',
    title: '12 Game-Changing Air Fryer Recipes You\'ll Make on Repeat',
    slug: 'game-changing-air-fryer-recipes',
    status: 'validating',
    wp_post_id: null,
    wp_permalink: null,
    error_message: null,
    created_at: '2026-04-14T07:05:00Z',
    completed_at: null,
    seo_title: '12 Game-Changing Air Fryer Recipes You\'ll Make on Repeat',
    meta_description: 'Transform your cooking with these 12 incredible air fryer recipes. From crispy chicken to perfect roasted veggies.',
    focus_keyword: 'air fryer recipes',
    content_markdown: '# 12 Game-Changing Air Fryer Recipes\n\nYour air fryer is about to become your best friend...\n\n## Crispy Air Fryer Chicken Wings\n\n...',
    content_html: '<h1>12 Game-Changing Air Fryer Recipes</h1><p>Your air fryer is about to become your best friend...</p><h2>Crispy Air Fryer Chicken Wings</h2><p>...</p>',
    hero_image_prompt: null,
    hero_image_url: null,
    detail_image_prompt: null,
    detail_image_url: null,
    pin_title: null,
    pin_description: null,
    pin_text_overlay: null,
    pin_image_url: null,
    category_name: 'Dinner Recipes',
    generation_attempts: 1,
    validation_errors: [],
    brain_output: null,
  },
  {
    id: 'ar-008-aaaa-bbbb-cccc-a88888888888',
    blog_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    run_id: null,
    keyword: 'weekend craft projects',
    title: '20 Easy Weekend Craft Projects That Anyone Can Do',
    slug: 'easy-weekend-craft-projects-anyone-can-do',
    status: 'publishing',
    wp_post_id: null,
    wp_permalink: null,
    error_message: null,
    created_at: '2026-04-14T09:00:00Z',
    completed_at: null,
    seo_title: '20 Easy Weekend Craft Projects for Beginners',
    meta_description: 'Looking for fun weekend craft projects? Try these 20 easy DIY ideas perfect for crafters of all skill levels.',
    focus_keyword: 'weekend craft projects',
    content_markdown: '# 20 Easy Weekend Craft Projects That Anyone Can Do\n\nCrafting is a wonderful way to spend your weekend...\n\n## Mason Jar Lanterns\n\n...',
    content_html: '<h1>20 Easy Weekend Craft Projects That Anyone Can Do</h1><p>Crafting is a wonderful way to spend your weekend...</p><h2>Mason Jar Lanterns</h2><p>...</p>',
    hero_image_prompt: 'A craft table with colorful DIY project materials',
    hero_image_url: 'https://fal.media/files/hero-craft-efg123.jpg',
    detail_image_prompt: 'Beautiful finished mason jar lanterns glowing in the dark',
    detail_image_url: 'https://fal.media/files/detail-jar-hij456.jpg',
    pin_title: '20 Weekend Crafts You\'ll Love',
    pin_description: 'Get creative this weekend with these 20 easy craft projects!',
    pin_text_overlay: '20 WEEKEND CRAFTS',
    pin_image_url: 'https://fal.media/files/pin-craft-klm789.jpg',
    category_name: 'Home Projects',
    generation_attempts: 1,
    validation_errors: [],
    brain_output: null,
  },
];

// ---------------------------------------------------------------------------
// Dashboard activity items (derived from mock data)
// ---------------------------------------------------------------------------

export interface ActivityItem {
  id: string;
  type: 'run_started' | 'run_completed' | 'article_published' | 'article_failed' | 'blog_connected';
  title: string;
  description: string;
  timestamp: string;
  blog_name?: string;
}

export const mockActivityItems: ActivityItem[] = [
  {
    id: 'act-001',
    type: 'run_started',
    title: 'Run Started',
    description: 'RUN-20260414-001 for The Weekend Folio',
    timestamp: '2026-04-14T08:00:15Z',
    blog_name: 'The Weekend Folio',
  },
  {
    id: 'act-002',
    type: 'article_published',
    title: 'Article Published',
    description: '"15 Weekend Brunch Ideas" published to The Weekend Folio',
    timestamp: '2026-04-14T08:22:30Z',
    blog_name: 'The Weekend Folio',
  },
  {
    id: 'act-003',
    type: 'run_completed',
    title: 'Run Completed',
    description: 'RUN-20260413-003 completed — 7/8 articles for Your Midnight Desk',
    timestamp: '2026-04-13T14:32:45Z',
    blog_name: 'Your Midnight Desk',
  },
  {
    id: 'act-004',
    type: 'article_failed',
    title: 'Article Failed',
    description: '"One Pot Meals" failed validation for Your Midnight Desk',
    timestamp: '2026-04-13T12:25:00Z',
    blog_name: 'Your Midnight Desk',
  },
  {
    id: 'act-005',
    type: 'article_published',
    title: 'Article Published',
    description: '"7 Comfort Food Classics" published to Your Midnight Desk',
    timestamp: '2026-04-13T12:18:45Z',
    blog_name: 'Your Midnight Desk',
  },
  {
    id: 'act-006',
    type: 'run_completed',
    title: 'Run Failed',
    description: 'RUN-20260412-002 failed — API rate limit for The Sunday Patio',
    timestamp: '2026-04-12T16:10:22Z',
    blog_name: 'The Sunday Patio',
  },
  {
    id: 'act-007',
    type: 'article_published',
    title: 'Article Published',
    description: '"Essential Spring Garden Tips" published to The Sunday Patio',
    timestamp: '2026-04-12T15:52:10Z',
    blog_name: 'The Sunday Patio',
  },
];

// ---------------------------------------------------------------------------
// Helper: get blog name by ID
// ---------------------------------------------------------------------------

export function getMockBlogName(blogId: string): string {
  const blog = mockBlogs.find((b) => b.id === blogId);
  return blog?.name ?? 'Unknown Blog';
}
