'use client';

import { PageHeader } from '@/components/layout';
import StatCard from '@/components/ui/StatCard';
import LiveDot from '@/components/ui/LiveDot';
import Badge from '@/components/ui/Badge';
import ActivityItem from '@/components/dashboard/ActivityItem';
import { useBlogs } from '@/hooks/useBlogs';
import { useRuns } from '@/hooks/useRuns';
import { useArticles } from '@/hooks/useArticles';
import { mockActivityItems } from '@/lib/mock-data';

export default function DashboardPage() {
  const { blogs } = useBlogs();
  const { runs } = useRuns();
  const { articles } = useArticles();

  // ---- Compute stat values ----

  // Blogs Connected: count of active blogs
  const blogsConnected = blogs.filter((b) => b.is_active).length;

  // Articles This Week: count articles created in the last 7 days
  const oneWeekAgo = new Date();
  oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);
  const articlesThisWeek = articles.filter(
    (a) => new Date(a.created_at) >= oneWeekAgo
  ).length;

  // Articles this week change percentage (mock: compare to previous week — derive from data)
  const twoWeeksAgo = new Date();
  twoWeeksAgo.setDate(twoWeeksAgo.getDate() - 14);
  const articlesPreviousWeek = articles.filter((a) => {
    const d = new Date(a.created_at);
    return d >= twoWeeksAgo && d < oneWeekAgo;
  }).length;
  const articlesChangePercent =
    articlesPreviousWeek > 0
      ? Math.round(
          ((articlesThisWeek - articlesPreviousWeek) / articlesPreviousWeek) * 100
        )
      : articlesThisWeek > 0
        ? 100
        : 0;

  // Active Runs: runs that are generating, running, or pending
  const activeRuns = runs.filter(
    (r) => r.status === 'generating' || r.status === 'running' || r.status === 'pending'
  );

  // Estimated articles being generated by active runs
  const generatingArticles = activeRuns.reduce(
    (sum, r) => sum + (r.articles_total - r.articles_completed),
    0
  );

  return (
    <div>
      <PageHeader title="Dashboard" />

      <div className="p-8">
        {/* ---- Stat Cards Row ---- */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Blogs Connected */}
          <StatCard
            value={blogsConnected}
            label="Blogs Connected"
          />

          {/* Articles This Week */}
          <StatCard
            value={articlesThisWeek}
            label="Articles This Week"
          >
            {articlesChangePercent !== 0 && (
              <span className="inline-flex items-center gap-1 mt-1">
                <Badge
                  variant="configured"
                  label={`↑ ${articlesChangePercent > 0 ? '+' : ''}${articlesChangePercent}%`}
                />
              </span>
            )}
          </StatCard>

          {/* Active Runs */}
          <StatCard
            value={activeRuns.length}
            label="Active Runs"
          >
            {activeRuns.length > 0 && (
              <span className="inline-flex items-center gap-2 mt-1 text-sm text-muted font-bold">
                <LiveDot size={8} />
                Generating ~{generatingArticles} articles
              </span>
            )}
          </StatCard>
        </div>

        {/* ---- Recent Activity Section ---- */}
        <div className="mt-10">
          <h2 className="text-lg font-black uppercase tracking-widest mb-4">
            Recent Activity
          </h2>

          <div className="bg-white border-[3px] border-base shadow-solid-md p-6">
            {mockActivityItems.length > 0 ? (
              <div>
                {mockActivityItems.map((item) => (
                  <ActivityItem key={item.id} item={item} />
                ))}
              </div>
            ) : (
              <p className="text-muted font-bold uppercase tracking-widest text-sm py-8 text-center">
                No Recent Activity
              </p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
